#!/bin/bash

# golang itself
GO_DL="https://dl.google.com/go/go1.12.9.linux-amd64.tar.gz"
GO_DIR=$HOME/Biba
GO_LANG_GZ="go-dl.tar.gz"

# application code
GO_DEV_BASE=$HOME/0_Dev/
GO_DEV_DIR="likurgs"
GIT_URL="git@bitbucket.org:vilishens/next.git"

# environment settings
GO_ROOT=$GO_DIR/go
GO_PATH=$GO_DEV_BASE$GO_DEV_DIR/go
SENDGRID_KEY="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"

# temporary environment settings
GO_PATH_TMP=$HOME/0_Dev/Kasatons


CURR_DIR=$(pwd)

echo '### GET golang'
./get_golang $CURR_DIR $GO_DL $GO_DIR
echo '### GET app code'
./get_source $CURR_DIR $GO_DEV_BASE $GO_DEV_DIR $GIT_URL 

echo '### SET environment'
export GOROOT=$GO_ROOT
export GOPATH=$GO_PATH
export PATH=$PATH:$GO_ROOT/bin
export SENDGRID_API_KEY=$SENDGRID_KEY

echo '### SET temporary GOLANG environment for golang packages'
export GOPATH=$GO_PATH_TMP
#create the language directory if it doesn't exist 
if [ ! -d $GO_PATH_TMP ]; then
  mkdir -p $GO_PATH_TMP
fi

echo '### GET additional golang packages'
./get_go_packages

echo '### COPY additinal packages to the permanent golang directory'
cp -r $GO_PATH_TMP/bin $GO_DIR/bin
# remove directory with the packages as all packages moved to golang directory
rm -rf $GO_PATH_TMP

echo '### SET back the permanent GOPATH'
export GOPATH=$GO_PATH

echo '### PREPARE application'
./prepare_app $CURR_DIR $GO_PATH

echo '### PREPARE .profile'
./set_profile $CURR_DIR $GO_ROOT $GO_PATH $SENDGRID_KEY

source $HOME/.profile

echo ""
echo ""
echo ""
echo ""
echo ""
echo ""
echo "**********************************************************"
echo "Please add the configuration file and restart Raspberry Pi"
echo ""
echo ""
echo ""

exit 7

